const VIEW_SIZE = 112;
const DISPLAY_SIZE = 96;
const SOURCE_FRAME = 96;

const WANDER_MARGIN = 12;
const FACE_FLIP_MIN_DX = 10;
const ARRIVE_EPS = 3;
const DRAG_THRESHOLD = 4;
const DRAG_VIEW_MARGIN = 8;

export {
  ARRIVE_EPS,
  DISPLAY_SIZE,
  DRAG_THRESHOLD,
  DRAG_VIEW_MARGIN,
  FACE_FLIP_MIN_DX,
  SOURCE_FRAME,
  VIEW_SIZE,
  WANDER_MARGIN,
};
